fix race in SharedCachedRegionProvider
Barteks2x/RegionLib pull request #15
Opened 2021-07-24 14:46 UTC by DaMatrix

**breaking API changes**

this is a total rewrite of SharedCachedRegionProvider, which now uses a different cache implementation which should be able to scale much better to larger thread counts *and* larger cache sizes.

i've spent about two days trying to make sure this code is race-free, and am pretty sure that it is. i've run a few large-scale tests (such as running writes in 10M random positions, ordered such that there will be plenty of writes on different threads accessing the same region close to each other, on 1000 threads) and found no problems.

2021-09-11 14:54 UTC, Barteks2x requested changes
Breaking changes are fine so if there is anything you kept in there only for backwards compatibility, feel free to remove it as long as a functionally equivalent replacement exists

2021-09-11 14:54 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +    Stream<K> allKeys() throws IOException;
tabs vs spaces

2021-09-11 14:54 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +
keep import order

2021-09-11 14:54 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +			//    regions as part of standard ones
The idea of fallback region providers was made with the additional intention of allowing on the fly conversion from older region formats. Some of the code for it is not quite as it should be, since it removes the data from old old region (which may or may not be ok). That's why I wanted to prevent duplicates. So it may be best to keep both as an option - one with possible duplicates and one that is slower and blocks, but doesn't allow duplicates.

2021-09-11 14:54 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +	 * Note that the returned {@link Stream} must be closed (using {@link Stream#close()}) once no longer needed.
Is there any way to avoid requiring the stream to be closed and automatically do it after a terminal operation? I REALLY don't like the idea of streams that have to be closed after use and it seems completely unnecessary.

2021-09-11 14:54 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/lib/provider/SharedCache.java
> +public class SharedCache implements Flushable, Closeable {
I'm not going to question any code in this class until I get to looking at it in IDE

2021-09-11 15:39 UTC, DaMatrix commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +	 * Note that the returned {@link Stream} must be closed (using {@link Stream#close()}) once no longer needed.
well, we could make the stream be backed by a custom `Spliterator` implementation which automatically closes resources once every value has been consumed, but since some `Stream` operations might not consume all values (such as `anyMatch(Predicate)`) that wouldn't work. finalizers are obviously a no-go. the only option which would work correctly in all circumstances would be to buffer every position in memory (in a `List` or something), and return a `Stream` over that, but that's dumb because the list of positions could easily be larger than available memory. i agree that `Stream#close()` is a gross API, but there's a good reason they included it...

2021-09-15 08:41 UTC, DaMatrix commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +    Stream<K> allKeys() throws IOException;
oops... i tried replacing all occurrences of 4 spaces with tabs, but it ended up affecting a bunch of code unaffected by this PR. can i fix this after this PR is merged to keep the diff readable?

2021-09-15 08:43 UTC, DaMatrix commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +
can intellij even be configured to do that? no combination of settings that i tried sorts sub-packages first.

2021-09-15 09:32 UTC, DaMatrix commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +			//    regions as part of standard ones
alright, will do. actually, i've just noticed that both implementations (as well as the method involving buffering all keys from all providers into a `Set`) have the possibility of *skipping* a key if an entry is moved from one provider to another. (which is, again, only an issue if using multiple save providers).

2021-09-15 12:09 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +
No idea. I will look at it and maybe fine the settings I used.

2021-09-15 12:10 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/region/IRegionProvider.java
> +    Stream<K> allKeys() throws IOException;
Ok

2021-09-15 12:15 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +			//    regions as part of standard ones
I think it may be best to keep the intentions more clean with fallback regions being read only and putting ext regions code into the base region file class. That way fallen xo providers would only be for reading and would be usable for on the fly region format conversions.

2021-09-15 12:42 UTC, DaMatrix commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +			//    regions as part of standard ones
i agree, that's probably how it should have been done in the first place :P

should i implement that in a separate PR or add it on to this one?

2021-09-15 14:35 UTC, Barteks2x commented on src/main/java/cubicchunks/regionlib/api/storage/SaveSection.java
> +			//    regions as part of standard ones
It can me added here

2021-12-20 21:33 UTC, merged